#!/usr/bin/env python3
"""
Scan the repository for source files and write their contents
into a single Markdown file. Each code block is preceded by
the file path as a heading.

Usage:
  python extract_code_to_markdown.py --out ALL_CODE.md

This script excludes common binary/build folders like node_modules
and .git, and only includes files with recognized code/config extensions.
"""
from __future__ import annotations

import argparse
import datetime
import os
from pathlib import Path
from typing import Dict, Iterable


EXCLUDE_DIRS = {"node_modules", ".git", "dist", "build", "venv", ".venv", "__pycache__", "coverage"}

EXT_LANG: Dict[str, str] = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "tsx",
    ".json": "json",
    ".css": "css",
    ".scss": "scss",
    ".html": "html",
    ".htm": "html",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".xml": "xml",
    ".md": "markdown",
    ".java": "java",
    ".c": "c",
    ".cpp": "cpp",
    ".h": "c",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".ini": "ini",
    ".env": "text",
}


def is_text_file(path: Path) -> bool:
    try:
        with open(path, "rb") as f:
            chunk = f.read(8192)
            if b"\0" in chunk:
                return False
    except Exception:
        return False
    return True


def find_code_files(root: Path) -> Iterable[Path]:
    for dirpath, dirnames, filenames in os.walk(root):
        # filter out excluded directories in-place to avoid walking them
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        for fn in filenames:
            p = Path(dirpath) / fn
            # skip symlinks that may point outside
            if p.is_symlink():
                continue
            if not is_text_file(p):
                continue
            if p.suffix.lower() in EXT_LANG:
                yield p


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except Exception:
        try:
            return path.read_text(encoding="latin-1")
        except Exception:
            return ""


def write_markdown(out: Path, files: Iterable[Path], root: Path) -> None:
    header = f"# Extracted Code\n\nGenerated by extract_code_to_markdown.py on {datetime.datetime.utcnow().isoformat()}Z\n\n"
    with out.open("w", encoding="utf-8") as f:
        f.write(header)
        for p in sorted(files):
            try:
                rel = p.relative_to(root).as_posix()
            except Exception:
                rel = p.as_posix()
            content = read_text(p)
            if not content.strip():
                continue
            lang = EXT_LANG.get(p.suffix.lower(), "text")
            f.write(f"## {rel}\n\n")
            f.write(f"```{lang}\n")
            f.write(content.rstrip("\n"))
            f.write("\n```")
            f.write("\n\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract repository code into a Markdown file")
    parser.add_argument("--out", "-o", default="ALL_CODE.md", help="Output markdown file")
    parser.add_argument("--root", "-r", default=".", help="Repository root to scan")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    out = Path(args.out).resolve()

    files = list(find_code_files(root))
    write_markdown(out, files, root)
    print(f"Wrote {len(files)} files to {out}")


if __name__ == "__main__":
    main()
