#!/usr/bin/env python3
"""
Recover files from a Markdown file generated by
extract_code_to_markdown.py.

Usage:
  python recover_code_from_markdown.py --in ALL_CODE.md --out recovery
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

# Regex to find markdown file headings and code blocks
# It looks for a line starting with '## ' followed by a path,
# then captures everything inside the following fenced code block.
CODE_BLOCK_RE = re.compile(
    r"^##\s+(?P<path>[^\n]+?)\s*\n\n```(?:[a-z]+)?\n(?P<code>.+?)\n```",
    re.DOTALL | re.MULTILINE,
)


def recover_files(md_content: str, out_dir: Path) -> int:
    """
    Parses a markdown file and restores the code files into the output directory.
    """
    count = 0
    for match in CODE_BLOCK_RE.finditer(md_content):
        path = match.group("path")
        code = match.group("code")

        # Sanitize path to prevent directory traversal issues
        if ".." in path:
            print(f"Skipping potentially unsafe path: {path}")
            continue

        file_path = out_dir / path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(code, encoding="utf-8")
        count += 1
        print(f"Recovered {file_path}")

    return count


def main() -> None:
    parser = argparse.ArgumentParser(description="Recover code from a Markdown file.")
    parser.add_argument("--in", dest="input_file", default="ALL_CODE.md", help="Input markdown file")
    parser.add_argument("--out", dest="output_dir", default="recovery", help="Output directory to restore files to")
    args = parser.parse_args()

    in_path = Path(args.input_file)
    out_path = Path(args.output_dir)

    if not in_path.exists():
        print(f"Error: Input file not found at {in_path}")
        return

    print(f"Reading from {in_path} and recovering to {out_path}...")
    md_content = in_path.read_text(encoding="utf-8")
    num_recovered = recover_files(md_content, out_path)
    print(f"\nSuccessfully recovered {num_recovered} files.")


if __name__ == "__main__":
    main()
